// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VF8GtLvWORM_Cdp4D0t_49lweMatGhU',
    appId: '1:650272267486:web:8d874cd0435fa3ebaef64f',
    messagingSenderId: '650272267486',
    projectId: 'bankingsystem-e1909',
    authDomain: 'bankingsystem-e1909.firebaseapp.com',
    storageBucket: 'bankingsystem-e1909.appspot.com',
    measurementId: 'G-8SMTHGSD6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1AM3DCBp8rPhK_VKgaTz_ydU7KUgkic',
    appId: '1:650272267486:android:e8e719a42b1890a7aef64f',
    messagingSenderId: '650272267486',
    projectId: 'bankingsystem-e1909',
    storageBucket: 'bankingsystem-e1909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5sDq_Sn4XWvMe4zSFbbUPwdDv65Dzj1E',
    appId: '1:650272267486:ios:74df3ced31a866deaef64f',
    messagingSenderId: '650272267486',
    projectId: 'bankingsystem-e1909',
    storageBucket: 'bankingsystem-e1909.appspot.com',
    iosBundleId: 'com.example.mobileBanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5sDq_Sn4XWvMe4zSFbbUPwdDv65Dzj1E',
    appId: '1:650272267486:ios:f5c487fc0121fb06aef64f',
    messagingSenderId: '650272267486',
    projectId: 'bankingsystem-e1909',
    storageBucket: 'bankingsystem-e1909.appspot.com',
    iosBundleId: 'com.example.mobileBanking.RunnerTests',
  );
}
